source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-feed"

# GitHub Pages
group :jekyll_plugins do
  gem "jekyll-github-metadata"
end

# Windows and JRuby does not include zoneinfo files
gem "tzinfo-data", platforms: [:mingw, :x64_mingw, :mswin, :jruby]
